Write aurorabridge integration test client
Summary:
Added `aurorabridge_test/` directory and working thrift client for sending Aurora RPCs to aurorabridge.
Also fixes aurorabridge bootstrapper to use v0 respool API, since v1 is not implemented yet.

Does not include any tests yet because the name -> job id table is not currently functional due to this
error: `unconfigured table job_name_to_id`.

However, I tested the client manually and ensured that we receive and process the RPCs correctly. So this
is all primed to have tests added once we're ready.

Reviewers: kevinxu, varung, apoorvaj, O521 Project Peloton: Add reviewers

Reviewed By: kevinxu, O521 Project Peloton: Add reviewers

Subscribers: jenkins

Differential Revision: https://code.uberinternal.com/D2411529