Bump up GO version to 1.8 for deb package build
Summary:
We are still using old GO version when building peloton CLI deb package.
However the recent change in tracker/manager.go requires GO 1.8.

jobmgr/tracked/manager.go:159: undefined: time.Until

Test Plan: (1) will kick off a Jenkins build after landing the change.

Reviewers: #peloton, mabansal, mu

Reviewed By: #peloton, mabansal, mu

Subscribers: jenkins, mu

Differential Revision: https://code.uberinternal.com/D1194261