Add ability to not deploy watchdog
Summary: Since some cluster owners do not wish to enable Peloton watchdogs (e.g. in WBU2 {D1542921}), our deployment tooling should be able to handle a cluster config from `peloton-cluster-config` without any `watchdog` YAML config. Existing watchdog in Aurora will have to be 'descheduled' from Aurora (e.g. `$ aurora cron deschedule pit1-devel01/peloton/production/watchdog`).

Test Plan:
With a `watchdog` config removed from a cluster config file, such as:
```
-watchdog:
-  enable_debug_logging: false
-  working_dir: /go/src/code.uber.internal/infra/peloton
-  cmdline: make integ-test TAGS='smoketest'
-  cron_schedule: \*/15 * * * *
```
Running the deployment tool gives the following error:
```
$ scripts/deploy.sh -c ~/Uber/dev/peloton-cluster-config/pit1-devel01/pit1-devel01.yaml
Traceback (most recent call last):
  File "tools/deploy/main.py", line 35, in <module>
    main()
  File "tools/deploy/main.py", line 25, in main
    cluster = Cluster.load(args.config)
  File "/Users/rcharles/gocode/src/code.uber.internal/infra/peloton/tools/deploy/cluster.py", line 75, in load
    return Cluster(**cfg)
  File "/Users/rcharles/gocode/src/code.uber.internal/infra/peloton/tools/deploy/cluster.py", line 60, in __init__
    app_cfg = getattr(self, app)
AttributeError: 'Cluster' object has no attribute 'watchdog'
```
With this patch, the deployment of `watchdog` is simply skipped.

Reviewers: #peloton, apoorvaj

Reviewed By: #peloton, apoorvaj

Subscribers: avyas, jenkins

Differential Revision: https://code.uberinternal.com/D1546375